apiVersion: v1
kind: Service
metadata:
  name: python-flask-getstart
spec:
  selector:
    app: python-flask-getstart
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
