apiVersion: v1
kind: Service
metadata:
  name: python-flask-getstart
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30000
  selector:
    app: python-flask-getstart
