apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-getstart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-flask-getstart
  template:
    metadata:
      labels:
        app: python-flask-getstart
    spec:
      initContainers:
      - name: install-dependencies
        image: python:3.9-slim
        command: ["/bin/sh", "-c"]
        args:
        - pip install flask -t /app &&
          cp /app.py/app
        volumeMounts:
        - name: app-volume
          mountPath: /app
      containers:
      - name: python-flask-getstart
        image: python:3.9-slim
        command: ["python"]
        args: ["/app/app.py"]
        volumeMounts:
        - name: app-volume
          mountPath: app
        ports:
        - containerPort: 5000
      volumes:
      - name: app-volume
        persistentVolumeClaim:
          claimName: app-volume-claim
