apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-01
  name: nginx-01
spec:
  containers:

  - image: nginx
    name: nginx-01
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-dir
      mountPath: /usr/share/nginx/html
    resources: {}

  - image: busybox
    name: busybox
    args:
      - sleep
      - "3600"
    volumeMounts:
    - name: shared-dir
      mountPath: /shared

  volumes:
  - name: shared-dir
    emptyDir: {}
